import BigQueryDoc from "@/components/BigQueryDoc";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Odoo Excel Connector Guide",
  description:
    "Learn step by step how to connect odoo with microsoft excel using techfinna excel connector. Comprehensive description with infographic images.",
};
const BigqueryDocPage = () => {
  const meta = {
    title: "Odoo Excel Connector Guide",
    desc: "Learn step by step how to connect odoo with microsoft excel using techfinna excel connector. Comprehensive description with infographic images.",
    url: "https://techfinna.com/guides/how-to-connect-excel-odoo/",
  };
  return (
    <>
      <head>
        <link rel="canonical" href={meta.url} />

        {/* <!-- Basic meta tags --> */}

        <meta name="robots" content="INDEX,FOLLOW" />

        {/* <!-- Facebook meta tags --> */}
        <meta name="og:title" content={meta.title} />
        <meta name="og:description" content={meta.desc} />

        <meta property="og:url" content={meta.url} />

        {/* <!-- Twtitter meta tags --> */}
        <meta name="twitter:title" content={meta.title} />
        <meta name="twitter:description" content={meta.desc} />
        <meta property="twitter:url" content={meta.url} />
      </head>
      <div className="px-3 text-black my-20 w-full mt-24">
        <div className="w-full md:w-[780px] mx-auto space-y-10">
          <h2 className="text-xl text-gray-500 font-semibold">
            How to connect Odoo with Microsoft Excel
          </h2>
          <h1 className="text-5xl font-bold">
            Microsoft Excel Odoo connector Installation and Setup Guide
          </h1>
          <hr></hr>

          {/* requirements */}
          <div className="space-y-3" id="req">
            <h3 className=" font-bold text-3xl"> Requirements:</h3>
            <ul className="leading-loose text-xl list-disc ml-[30px]">
              <li>
                {" "}
                Odoo Versions Supported: 12, 13, 14, 15, 16, 17, 18 (Enterprise
                or Community)
              </li>
              <li> Microsoft Excel installed in your OS</li>
              <li>Downloaded Excel Odoo Connector by Techfinna</li>
              <li>
                URL and Access Token generated by Excel Odoo Connector by
                Techfinna{" "}
              </li>
            </ul>
          </div>
          {/* installation */}
          <div className="space-y-3" id="install">
            <h3 className=" font-bold text-3xl"> Installation:</h3>
            <ul className="leading-loose text-xl list-disc ml-[30px]">
              <li> Download the Odoo to Excel Connector module from </li>
              <div className="border rounded-sm my-1 bg-[#F9F9F9] p-[22px]">
                <a
                  target="_blank"
                  className="font-sans break-words hover:text-[#2462D0]"
                  href="https://apps.odoo.com/apps/modules/18.0/excel_connector"
                >
                  https://apps.odoo.com/apps/modules/18.0/excel_connector
                </a>
              </div>
              <img
                className="img-fluid img my-5"
                src="/images/excel-connector/downloadExcel.png"
                alt="excel-odoo-connector"
              />
              <p className="font-semibold text-center text-3xl">OR</p>
              <div className="border rounded-sm my-1 bg-[#F9F9F9] p-[22px]">
                <a
                  target="_blank"
                  className="font-sans break-words hover:text-[#2462D0]"
                  href="https://techfinna.com/odoo-excel-connector/"
                >
                  https://techfinna.com/odoo-excel-connector/
                </a>
              </div>
              <img
                className="img-fluid img my-5"
                src="/images/excel-connector/excel-website.png"
                alt="excel-odoo-connector"
              />
            </ul>
          </div>
          {/* config */}
          <div className="space-y-3" id="config">
            <h3 className=" font-bold text-3xl">
              {" "}
              Odoo Excel Connector Setup:
            </h3>
            <h4 className="font-bold text-xl pt-2" id="1.1">
              1.1. Copy & Paste manifest.xml:
            </h4>
            <ul className="leading-loose text-xl list-disc ml-[30px]">
              <li>
                {" "}
                After installation, copy "manifest.xml" from the module
                directory.{" "}
              </li>

              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/copyXml.png"
                alt="excel-odoo-connector"
              />
              <li> Paste the file in this directory </li>
              <div className="border rounded-sm my-1 bg-[#F9F9F9] p-[22px]">
                <p className="font-sans break-words hover:text-[#2462D0]">
                  "C:\\Manifest\manifest.xml"
                </p>
              </div>
            </ul>
            <h4 className="font-bold text-xl pt-2" id="1.2">
              1.2. Give Folder Access:
            </h4>
            <ul className="leading-loose text-xl list-disc ml-[30px]">
              <li>
                {" "}
                Right click inside the folder & click on "Give Access" to
                "Specific People"{" "}
              </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/giveAccess.png"
                alt="excel-odoo-connector"
              />
              <li>
                {" "}
                Select the profile you are using in your operating system &
                click on "Share"{" "}
              </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/shareAccess.png"
                alt="excel-odoo-connector"
              />
              <li>
                {" "}
                Copy the path of the shared folder. For eg"\\{`{PC_NAME}`}
                \Manifest"
              </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/copyPath.png"
                alt="excel-odoo-connector"
              />
            </ul>
            <h4 className="font-bold text-2xl pt-2" id="1.3">
              1.3. Open Microsoft Excel & change settings:
            </h4>
            <ul className="leading-loose text-xl list-disc ml-[30px]">
              <li className="text-xl py-3 font-semibold">
                Open Excel & click on "Options"{" "}
              </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/openOptions.png"
                alt="excel-odoo-connector"
              />
              <li className="text-xl py-3 font-semibold">
                Select "Trust Center" & open "Trust Center Settings.."{" "}
              </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/trustCenter.png"
                alt="excel-odoo-connector"
              />
              <li className="text-xl py-3 font-semibold">
                Select "Trust Add-in Catalogs" & paste the shared folder path in
                the "Catalog URL" then click on "Add Catalog"{" "}
              </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/addXmlPath.png"
                alt="excel-odoo-connector"
              />
              <li className="text-xl py-3 font-semibold">
                Select "Show in Menu" & then click "Ok"{" "}
              </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/trustCatalog.png"
                alt="excel-odoo-connector"
              />
              <p className="text-xl text-gray-600">
                <b className="underline text-black">Note:</b> (If you have
                shared the access of the folder properly, the Catalog URL will
                be added here smoothly)
              </p>
            </ul>
            <h4 className="font-bold text-xl pt-2" id="1.4">
              1.4. Restart Microsoft Excel
            </h4>
            <h4 className="font-bold text-xl pt-2" id="1.2">
              1.5. Open Excel & Add Connector:
            </h4>
            <ul className="leading-loose text-xl list-disc ml-[30px]">
              <li>
                {" "}
                Open new excel workbook & click on Add-ins on the top right of
                the "Home" Menu{" "}
              </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/openBlankWorkbook.png"
                alt="excel-odoo-connector"
              />
              <li> Click on "More Add-ins" </li>
              <img
                className=" mx-auto img-fluid img my-5 shadow"
                src="/images/excel-connector/clickMoreAddIns.png"
                alt="excel-odoo-connector"
                width={"380px"}
              />
              <li>
                {" "}
                Open "Shared Folder" & select the connector like shown below{" "}
              </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/addCatalog.png"
                alt="excel-odoo-connector"
              />
            </ul>
            <h4 className="font-bold text-xl pt-2" id="1.2">
              1.6. Connector is successfully added:
            </h4>
            <ul className="leading-loose text-xl list-disc ml-[30px]">
              <li>
                {" "}
                You can view the connector on the top right corner named "Show
                Taskpane". Enter URL & Token to connect with your Odoo data{" "}
              </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/enter-url.png"
                alt="excel-odoo-connector"
              />
              <li> Select tables to fetch </li>
              <img
                className=" mx-auto img-fluid img my-5 shadow"
                src="/images/excel-connector/fetch-tables.png"
                alt="excel-odoo-connector"
              />
              <li> You can also execute complex SQL query to fetch data </li>
              <img
                className="img-fluid img my-5 shadow"
                src="/images/excel-connector/run-sql.png"
                alt="excel-odoo-connector"
              />
            </ul>
          </div>
        </div>
      </div>
    </>
  );
};

export default BigqueryDocPage;
